"""image table

Revision ID: 170e7ea381ac
Revises: ee2b3865d2d0
Create Date: 2024-04-30 21:42:38.937076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170e7ea381ac'
down_revision = 'ee2b3865d2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=256), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_post_id'))

    op.drop_table('image')
    # ### end Alembic commands ###
