"""reply table

Revision ID: 65709575dbc9
Revises: 71b059243d80
Create Date: 2024-05-16 21:20:47.432029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65709575dbc9'
down_revision = '71b059243d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reply_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_reply_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reply_user_id'))
        batch_op.drop_index(batch_op.f('ix_reply_timestamp'))
        batch_op.drop_index(batch_op.f('ix_reply_post_id'))

    op.drop_table('reply')
    # ### end Alembic commands ###
