"""address table

Revision ID: af3926370d4d
Revises: 170e7ea381ac
Create Date: 2024-05-09 17:55:06.787625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3926370d4d'
down_revision = '170e7ea381ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('street', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=32), nullable=False),
    sa.Column('postcode', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_address_id'), ['address_id'], unique=False)
        batch_op.create_foreign_key(None, 'address', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_address_id'))
        batch_op.drop_column('address_id')

    op.drop_table('address')
    # ### end Alembic commands ###
